version: '3'
services:
    web:
        image: misbahulard/nginx
        environment:
            - SERVICE_PORTS=80
        ports:
            - 80
        volumes:
            - wp_content:/var/www/html/wp-content/uploads
        networks:
            - internals
    php:
        image: misbahulard/phpfpm
        environment:
            USE_REDIS: "yes"
        volumes:
            - wp_content:/var/www/html/wp-content/uploads
        networks:
            - internals
    mariadb:
        image: misbahulard/mariadb
        volumes:
            - /data/mysql:/var/lib/mysql
        networks:
            - internals
    redis:
        image: misbahulard/redis
        networks:
            - internals
    proxy:
        image: dockercloud/haproxy
        environment:
          - BALANCE=leastconn
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 80:80
        networks:
          - internals
        deploy:
          placement:
            constraints: [node.role == manager]
networks:
    internals:
        driver: overlay
volumes:
    wp_content:
        driver_opts:
            type: "nfs"
            o: "addr=192.168.56.101"
            device: ":/var/nfs/wp-content"
