version: '3.2'
services:
    web:
        image: misbahulard/nginx
        environment:
            - PHP_HOST=blibli_php
            - DB_HOST=blibli_mariadb
        ports:
            - target: 80
              published: 8080
              protocol: tcp
        volumes:
            - type: volume
              source: wp-content
              target: /var/www/html/wp-content
        networks:
            - internal
    php:
        image: misbahulard/phpfpm
        environment:
            - USE_REDIS=yes
            - REDIS_HOST=blibli_redis
            - DB_HOST=blibli_mariadb
        volumes:
            - type: volume
              source: wp-content
              target: /var/www/html/wp-content
        networks:
            - internal
    mariadb:
        image: misbahulard/mariadb
        volumes:
            - type: volume
              source: mysql-data
              target: /var/lib/mysql
        networks:
            - internal
    redis:
        image: misbahulard/redis
        networks:
            - internal
networks:
    internal:
        driver: overlay
volumes:
    wp-content:
        driver_opts:
            type: "nfs"
            o: "addr=192.168.56.101,rw"
            device: ":/var/nfs/wp-content"
    mysql-data:
        driver_opts:
            type: "nfs"
            o: "addr=192.168.56.101,rw"
            device: ":/var/nfs/mysql"
