version: '3.2'
services:
    nginx:
        image: misbahulard/nginx
        environment:
            DB_HOST: "blibli_mariadb"
            PHP_HOST: "blibli_php"
        depends_on:
            - php
        ports:
            - target: 80
              published: 8080
              protocol: tcp
        volumes:
            - wp-content:/var/www/html/wp-content
        networks:
            - internal
        command: dockerize -wait tcp://php:9000 nginx -g "daemon off;"
    php:
        image: misbahulard/phpfpm
        environment:
            USE_REDIS: "yes"
            DB_HOST: "blibli_mariadb"
            REDIS_HOST: "blibli_redis"
        volumes:
            - wp-content:/var/www/html/wp-content
        networks:
            - internal
    mariadb:
        image: misbahulard/mariadb
        volumes:
            - /data/mysql:/var/lib/mysql
        networks:
            - internal
        deploy:
            placement:
                constraints:
                    - node.labels.type == db
    redis:
        image: misbahulard/redis
        networks:
            - internal
networks:
    internal:
        driver: overlay
volumes:
    wp-content:
        driver_opts:
            type: "nfs"
            o: "addr=192.168.56.100,rw"
            device: ":/var/nfs/wp-content"
#    mysql-data:
#        - /data/mysql:/var/lib/mysql
